name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Terraform
    # This job runs on Linux
    runs-on: hashicorp/terraform:light
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Init
        run: terraform init
      - name: Plan
        run: terraform plan
